# command line: main.py --config config/uav-csv1/default.yaml --work-dir work_dir/uav1/skmixf_joint --device 6 7

base_lr: 0.2
batch_size: 128
config: config/u1.yaml
device:
- 6
- 7
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
model: model.ske_mixf.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 140
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 80
save_interval: 1
save_score: True
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 110
- 120
test_batch_size: 4599
test_feeder_args:
  bone: false
  data_path: data/data
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/data
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: false
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir: ./output/skmixf__V1_J
